name: ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
